/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/961nHKIpsMR
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function base() {
  return (
    <main className="lg:grid lg:grid-cols-2 gap-10 p-6 xl:p-10">
      <aside className="flex flex-col items-center space-y-6">
        <Avatar className="h-48 w-48">
          <AvatarImage
            alt="Artist's Name"
            className="object-cover object-center rounded-full"
            src="/placeholder-avatar.jpg"
          />
          <AvatarFallback>AN</AvatarFallback>
        </Avatar>
        <div className="text-center space-y-2">
          <h1 className="text-3xl font-bold">Artist's Name</h1>
          <p className="text-gray-500 dark:text-gray-400">
            A brief description about the artist. This is a place to share a little bit about their background, their
            art style, and what inspires them.
          </p>
        </div>
        <div className="flex flex-col space-y-2">
          <Link className="underline" href="#">
            Terms of Service
          </Link>
          <Link className="underline" href="#">
            Commission Information
          </Link>
        </div>
        <div className="flex space-x-2">
          <Button variant="link">
            <a href="#">
              <MailboxIcon className="w-4 h-4" />
            </a>
          </Button>
          <Button variant="link">
            <a href="#">
              <LinkedinIcon className="w-4 h-4" />
            </a>
          </Button>
          <Button variant="link">
            <a href="#">
              <InstagramIcon className="w-4 h-4" />
            </a>
          </Button>
        </div>
      </aside>
      <section className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
        <Card className="col-span-1">
          <CardContent>
            <img
              alt="Artwork 1"
              className="w-full h-full object-cover object-center"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
          </CardContent>
        </Card>
        <Card className="col-span-1">
          <CardContent>
            <img
              alt="Artwork 2"
              className="w-full h-full object-cover object-center"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
          </CardContent>
        </Card>
        <Card className="col-span-1">
          <CardContent>
            <img
              alt="Artwork 3"
              className="w-full h-full object-cover object-center"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
          </CardContent>
        </Card>
        <Card className="col-span-1">
          <CardContent>
            <img
              alt="Artwork 4"
              className="w-full h-full object-cover object-center"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
          </CardContent>
        </Card>
      </section>
    </main>
  )
}


function MailboxIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 17a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9.5C2 7 4 5 6.5 5H18c2.2 0 4 1.8 4 4v8Z" />
      <polyline points="15,9 18,9 18,11" />
      <path d="M6.5 5C9 5 11 7 11 9.5V17a2 2 0 0 1-2 2v0" />
      <line x1="6" x2="7" y1="10" y2="10" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}
